# Generated by Django 3.0.7 on 2020-06-06 03:15

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Posts',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('page', models.ImageField(upload_to='')),
                ('description', models.TextField()),
                ('link', models.CharField(max_length=200)),
                ('date', models.DateField()),
            ],
        ),
    ]
