# Generated by Django 3.0.7 on 2020-06-06 04:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0002_auto_20200606_0659'),
    ]

    operations = [
        migrations.RenameField(
            model_name='posts',
            old_name='date',
            new_name='date_posted',
        ),
        migrations.RenameField(
            model_name='posts',
            old_name='page',
            new_name='image_page',
        ),
    ]
