# Generated by Django 3.0.7 on 2020-06-07 21:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0002_rates'),
    ]

    operations = [
        migrations.AlterField(
            model_name='posts',
            name='link',
            field=models.URLField(),
        ),
    ]
